
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 29 19:10:17 EDT 2012
//----------------------------------------------------

package hog_parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int LESS_EQL = 12;
  public static final int MAP = 46;
  public static final int DIVIDE = 8;
  public static final int UMINUS = 2;
  public static final int L_PAREN = 50;
  public static final int CASE = 31;
  public static final int R_PAREN = 51;
  public static final int DECR = 3;
  public static final int INT = 19;
  public static final int INCR = 4;
  public static final int FOR = 37;
  public static final int LESS = 10;
  public static final int MINUS = 5;
  public static final int NOT = 35;
  public static final int AND = 33;
  public static final int ELSEIF = 42;
  public static final int IN = 39;
  public static final int OR = 34;
  public static final int COMMA = 54;
  public static final int BOOL = 18;
  public static final int SEMICOL = 52;
  public static final int GRTR = 11;
  public static final int PLUS = 6;
  public static final int MAIN = 45;
  public static final int IF = 40;
  public static final int ASSIGN = 16;
  public static final int GRTR_EQL = 13;
  public static final int DOT = 24;
  public static final int ID = 26;
  public static final int EOF = 0;
  public static final int INT_CONST = 27;
  public static final int error = 1;
  public static final int NEWLINE = 55;
  public static final int TEXT_LITERAL = 25;
  public static final int MOD = 9;
  public static final int BREAK = 30;
  public static final int VOID = 22;
  public static final int SWITCH = 43;
  public static final int COL = 53;
  public static final int REAL = 20;
  public static final int TIMES = 7;
  public static final int ARROW = 23;
  public static final int L_BRACE = 48;
  public static final int FOREACH = 38;
  public static final int ELSE = 41;
  public static final int R_BRACE = 49;
  public static final int FUNCTIONS = 44;
  public static final int WHILE = 36;
  public static final int LIST = 21;
  public static final int DEFAULT = 32;
  public static final int REAL_CONST = 28;
  public static final int BOOL_CONST = 29;
  public static final int TEXT = 17;
  public static final int REDUCE = 47;
  public static final int NOT_EQLS = 15;
  public static final int DBL_EQLS = 14;
}

