/* The following code was generated by JFlex 1.4.3 on 4/13/12 2:41 PM */

package front_end;

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 4/13/12 2:41 PM from the specification file
 * <tt>/Volumes/Macintosh HD/Users/sam/personal/2012/courses/plt_4115/hog/Hog/src/front_end/Lexer.jflex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\14\1\6\25\0\1\14\1\62\1\4\1\11\1\0\1\50"+
    "\1\0\1\7\1\53\1\54\1\44\1\45\1\52\1\46\1\10\1\47"+
    "\12\2\1\63\1\51\1\61\1\60\1\57\1\0\1\36\5\1\1\37"+
    "\6\1\1\41\4\1\1\43\10\1\1\55\1\5\1\56\1\0\1\3"+
    "\1\0\1\15\1\33\1\35\1\17\1\20\1\24\1\1\1\30\1\23"+
    "\2\1\1\21\1\1\1\16\1\25\1\42\1\1\1\26\1\22\1\31"+
    "\1\40\1\34\1\27\1\32\2\1\1\12\1\0\1\13\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\1\2\2\1\4\1\2\1\5"+
    "\1\2\1\6\1\7\15\3\1\2\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\2\1\26\1\3\1\0\1\27"+
    "\1\30\3\0\5\3\1\31\1\32\2\3\1\33\6\3"+
    "\3\0\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\0\1\44\1\45\3\3\1\46\1\3\1\47"+
    "\7\3\3\0\1\50\1\51\1\52\2\3\1\53\2\3"+
    "\1\54\1\55\1\56\1\57\2\0\1\60\1\0\2\3"+
    "\1\61\1\3\1\62\1\0\1\63\1\0\1\64\1\65"+
    "\1\66\3\0\1\67\2\0\1\70";

  private static int [] zzUnpackAction() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\u0104\0\64\0\u0138"+
    "\0\u016c\0\u01a0\0\64\0\64\0\u01d4\0\u0208\0\u023c\0\u0270"+
    "\0\u02a4\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410"+
    "\0\u0444\0\u0478\0\64\0\u04ac\0\u04e0\0\64\0\64\0\64"+
    "\0\64\0\64\0\64\0\64\0\64\0\u0514\0\u0548\0\u057c"+
    "\0\u05b0\0\64\0\u05e4\0\u0104\0\u016c\0\u0104\0\u0618\0\u064c"+
    "\0\u0680\0\u06b4\0\u06e8\0\u071c\0\u0750\0\u0784\0\u07b8\0\u05e4"+
    "\0\u07ec\0\u0820\0\u05e4\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0924"+
    "\0\u0958\0\u098c\0\u09c0\0\u09f4\0\64\0\64\0\64\0\64"+
    "\0\64\0\64\0\64\0\64\0\u0a28\0\u05e4\0\u05e4\0\u0a5c"+
    "\0\u0a90\0\u0ac4\0\u05e4\0\u0af8\0\u05e4\0\u0b2c\0\u0b60\0\u0b94"+
    "\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u0ccc\0\u0d00\0\64"+
    "\0\u0d34\0\u05e4\0\u0d68\0\u0d9c\0\u05e4\0\u0dd0\0\u0e04\0\u05e4"+
    "\0\u05e4\0\u05e4\0\u05e4\0\u0e38\0\u0e6c\0\64\0\u0ea0\0\u0ed4"+
    "\0\u0f08\0\u05e4\0\u0f3c\0\u05e4\0\u0f70\0\64\0\u0fa4\0\u05e4"+
    "\0\u05e4\0\u05e4\0\u0fd8\0\u100c\0\u1040\0\64\0\u1074\0\u10a8"+
    "\0\64";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\2\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\7\1\15\1\16\1\3"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\3\1\27\1\3\1\30\1\31\1\3\1\32\5\3"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\65\0\3\53\1\54\10\0\21\53\1\0\5\53\22\0"+
    "\1\4\5\0\1\55\57\0\1\54\57\0\4\54\1\56"+
    "\1\57\1\54\1\0\54\54\6\60\1\0\55\60\2\0"+
    "\1\55\73\0\1\61\52\0\3\53\1\54\10\0\1\53"+
    "\1\62\17\53\1\0\5\53\21\0\3\53\1\54\10\0"+
    "\10\53\1\63\10\53\1\0\5\53\21\0\3\53\1\54"+
    "\10\0\4\53\1\64\14\53\1\0\5\53\21\0\3\53"+
    "\1\54\10\0\6\53\1\65\12\53\1\0\5\53\21\0"+
    "\3\53\1\54\10\0\12\53\1\66\6\53\1\0\5\53"+
    "\21\0\3\53\1\54\10\0\1\53\1\67\5\53\1\70"+
    "\11\53\1\0\5\53\21\0\3\53\1\54\10\0\1\71"+
    "\7\53\1\72\10\53\1\0\5\53\21\0\3\53\1\54"+
    "\10\0\11\53\1\73\7\53\1\0\5\53\21\0\3\53"+
    "\1\54\10\0\3\53\1\74\15\53\1\0\5\53\21\0"+
    "\3\53\1\54\10\0\13\53\1\75\5\53\1\0\5\53"+
    "\21\0\3\53\1\54\10\0\3\53\1\76\5\53\1\77"+
    "\7\53\1\0\5\53\21\0\3\53\1\54\10\0\10\53"+
    "\1\100\10\53\1\0\5\53\21\0\3\53\1\54\10\0"+
    "\10\53\1\101\10\53\1\0\5\53\57\0\1\102\1\0"+
    "\1\103\1\0\1\104\65\0\1\105\64\0\1\106\10\0"+
    "\1\107\64\0\1\110\63\0\1\111\63\0\1\112\63\0"+
    "\1\113\4\0\3\53\11\0\21\53\1\0\5\53\20\0"+
    "\6\54\1\0\55\54\7\0\1\114\54\0\13\61\1\115"+
    "\50\61\1\0\3\53\11\0\2\53\1\116\16\53\1\0"+
    "\5\53\21\0\3\53\11\0\14\53\1\117\4\53\1\0"+
    "\5\53\21\0\3\53\11\0\5\53\1\120\13\53\1\0"+
    "\5\53\21\0\3\53\11\0\5\53\1\121\13\53\1\0"+
    "\5\53\21\0\3\53\11\0\6\53\1\122\12\53\1\0"+
    "\5\53\21\0\3\53\11\0\14\53\1\123\4\53\1\0"+
    "\5\53\21\0\3\53\11\0\4\53\1\124\14\53\1\0"+
    "\5\53\21\0\3\53\11\0\11\53\1\125\7\53\1\0"+
    "\5\53\21\0\3\53\11\0\1\126\13\53\1\127\4\53"+
    "\1\0\5\53\21\0\3\53\11\0\6\53\1\130\12\53"+
    "\1\0\5\53\21\0\3\53\11\0\15\53\1\131\3\53"+
    "\1\0\5\53\21\0\3\53\11\0\21\53\1\0\1\53"+
    "\1\132\3\53\21\0\3\53\11\0\10\53\1\133\10\53"+
    "\1\0\5\53\21\0\3\53\11\0\6\53\1\134\12\53"+
    "\1\0\5\53\60\0\1\135\40\0\1\136\66\0\1\137"+
    "\54\0\1\140\53\0\3\53\11\0\3\53\1\141\15\53"+
    "\1\0\5\53\21\0\3\53\11\0\14\53\1\142\4\53"+
    "\1\0\5\53\21\0\3\53\11\0\14\53\1\143\4\53"+
    "\1\0\5\53\21\0\3\53\11\0\5\53\1\144\13\53"+
    "\1\0\5\53\21\0\3\53\11\0\4\53\1\145\14\53"+
    "\1\0\5\53\21\0\3\53\11\0\21\53\1\0\1\53"+
    "\1\146\3\53\21\0\3\53\11\0\4\53\1\147\14\53"+
    "\1\0\5\53\21\0\3\53\11\0\14\53\1\150\4\53"+
    "\1\0\5\53\21\0\3\53\11\0\3\53\1\151\15\53"+
    "\1\0\5\53\21\0\3\53\11\0\4\53\1\152\14\53"+
    "\1\0\5\53\21\0\3\53\11\0\2\53\1\153\16\53"+
    "\1\0\5\53\36\0\1\154\70\0\1\155\16\0\1\156"+
    "\40\0\1\157\45\0\3\53\11\0\6\53\1\160\12\53"+
    "\1\0\5\53\21\0\3\53\11\0\20\53\1\161\1\0"+
    "\5\53\21\0\3\53\11\0\3\53\1\162\15\53\1\0"+
    "\5\53\21\0\3\53\11\0\11\53\1\163\7\53\1\0"+
    "\5\53\21\0\3\53\11\0\3\53\1\164\15\53\1\0"+
    "\5\53\55\0\1\165\44\0\1\166\105\0\1\167\24\0"+
    "\3\53\11\0\7\53\1\170\11\53\1\0\5\53\21\0"+
    "\3\53\11\0\13\53\1\171\5\53\1\0\5\53\21\0"+
    "\3\53\11\0\1\53\1\172\17\53\1\0\5\53\51\0"+
    "\1\173\67\0\1\174\51\0\1\175\60\0\1\176\70\0"+
    "\1\177\54\0\1\200\67\0\1\201\41\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4316];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\4\1\1\11\3\1\2\11\16\1\1\11"+
    "\2\1\10\11\4\1\1\11\1\1\1\0\2\1\3\0"+
    "\20\1\3\0\10\11\1\0\17\1\3\0\1\11\13\1"+
    "\2\0\1\11\1\0\5\1\1\0\1\11\1\0\3\1"+
    "\3\0\1\11\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

/**
 * Return a new Symbol with the given token id, and with the current line and
 * column numbers.
 */
Symbol newSym(int tokenId) {
    return new Symbol(tokenId, yyline, yycolumn);
}

/**
 * Return a new Symbol with the given token id, the current line and column
 * numbers, and the given token value.  The value is used for tokens such as
 * identifiers and numbers.
 */
Symbol newSym(int tokenId, Object value) {
    return new Symbol(tokenId, yyline, yycolumn, value);
}



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 138) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 54: 
          { return newSym(sym.RETURN);
          }
        case 57: break;
        case 47: 
          { return newSym(sym.VOID);
          }
        case 58: break;
        case 44: 
          { return newSym(sym.TEXT);
          }
        case 59: break;
        case 13: 
          { return newSym(sym.SEMICOL);
          }
        case 60: break;
        case 51: 
          { return newSym(sym.MAIN);
          }
        case 61: break;
        case 50: 
          { return newSym(sym.WHILE);
          }
        case 62: break;
        case 18: 
          { return newSym(sym.R_BRKT);
          }
        case 63: break;
        case 41: 
          { return newSym(sym.ELSE);
          }
        case 64: break;
        case 32: 
          { return newSym(sym.DBL_EQLS);
          }
        case 65: break;
        case 16: 
          { return newSym(sym.R_PAREN);
          }
        case 66: break;
        case 33: 
          { return newSym(sym.LESS_EQL);
          }
        case 67: break;
        case 52: 
          { return newSym(sym.ELSEIF);
          }
        case 68: break;
        case 6: 
          { return newSym(sym.L_BRACE);
          }
        case 69: break;
        case 46: 
          { return newSym(sym.BOOL);
          }
        case 70: break;
        case 39: 
          { return newSym(sym.FOR);
          }
        case 71: break;
        case 10: 
          { return newSym(sym.MINUS);
          }
        case 72: break;
        case 53: 
          { return newSym(sym.SWITCH);
          }
        case 73: break;
        case 34: 
          { return newSym(sym.NOT_EQLS);
          }
        case 74: break;
        case 4: 
          { /* Ignore whitespace. */
          }
        case 75: break;
        case 19: 
          { return newSym(sym.GRTR);
          }
        case 76: break;
        case 29: 
          { return newSym(sym.DECR);
          }
        case 77: break;
        case 14: 
          { return newSym(sym.COMMA);
          }
        case 78: break;
        case 26: 
          { return newSym(sym.IF);
          }
        case 79: break;
        case 56: 
          { return newSym(sym.FUNCTIONS);
          }
        case 80: break;
        case 24: 
          { return newSym(sym.TEXT_LITERAL, new String(yytext()));
          }
        case 81: break;
        case 45: 
          { return newSym(sym.BOOL_CONST, true);
          }
        case 82: break;
        case 43: 
          { return newSym(sym.REAL);
          }
        case 83: break;
        case 27: 
          { return newSym(sym.OR);
          }
        case 84: break;
        case 3: 
          { return newSym(sym.ID, new String(yytext()));
          }
        case 85: break;
        case 25: 
          { return newSym(sym.IN);
          }
        case 86: break;
        case 28: 
          { return newSym(sym.INCR);
          }
        case 87: break;
        case 15: 
          { return newSym(sym.L_PAREN);
          }
        case 88: break;
        case 23: 
          { return newSym(sym.REAL_CONST, new Double(yytext()));
          }
        case 89: break;
        case 11: 
          { return newSym(sym.DIVIDE);
          }
        case 90: break;
        case 5: 
          { return newSym(sym.DOT);
          }
        case 91: break;
        case 17: 
          { return newSym(sym.L_BRKT);
          }
        case 92: break;
        case 55: 
          { return newSym(sym.REDUCE);
          }
        case 93: break;
        case 35: 
          { return newSym(sym.CHAR, new Character(yytext().charAt(1)));
          }
        case 94: break;
        case 31: 
          { return newSym(sym.GRTR_EQL);
          }
        case 95: break;
        case 7: 
          { return newSym(sym.R_BRACE);
          }
        case 96: break;
        case 1: 
          { return newSym(sym.INT_CONST, new Integer(yytext()));
          }
        case 97: break;
        case 42: 
          { return newSym(sym.LIST);
          }
        case 98: break;
        case 22: 
          { return newSym(sym.COL);
          }
        case 99: break;
        case 38: 
          { return newSym(sym.INT);
          }
        case 100: break;
        case 49: 
          { return newSym(sym.BOOL_CONST, false);
          }
        case 101: break;
        case 48: 
          { return newSym(sym.MAP);
          }
        case 102: break;
        case 37: 
          { return newSym(sym.NOT);
          }
        case 103: break;
        case 36: 
          { return newSym(sym.AND);
          }
        case 104: break;
        case 30: 
          { return newSym(sym.ARROW);
          }
        case 105: break;
        case 2: 
          { System.out.println("Illegal char, '" + yytext() +
                    "' line: " + yyline + ", column: " + yychar);
          }
        case 106: break;
        case 9: 
          { return newSym(sym.PLUS);
          }
        case 107: break;
        case 12: 
          { return newSym(sym.MOD);
          }
        case 108: break;
        case 40: 
          { /* For this stand-alone lexer, print out comments. */
                  System.out.println("Recognized comment: " + yytext());
          }
        case 109: break;
        case 21: 
          { return newSym(sym.LESS);
          }
        case 110: break;
        case 20: 
          { return newSym(sym.ASSIGN);
          }
        case 111: break;
        case 8: 
          { return newSym(sym.TIMES);
          }
        case 112: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
