
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 13 14:04:12 EDT 2012
//----------------------------------------------------

package front_end;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LESS_EQL = 13;
  public static final int MAP = 48;
  public static final int DIVIDE = 9;
  public static final int CHAR = 26;
  public static final int UMINUS = 2;
  public static final int L_PAREN = 54;
  public static final int CASE = 33;
  public static final int R_PAREN = 55;
  public static final int DECR = 3;
  public static final int INT = 20;
  public static final int INCR = 4;
  public static final int FOR = 39;
  public static final int LESS = 11;
  public static final int MINUS = 6;
  public static final int NOT = 37;
  public static final int AND = 35;
  public static final int ELSEIF = 44;
  public static final int IN = 41;
  public static final int OR = 36;
  public static final int COMMA = 58;
  public static final int BOOL = 19;
  public static final int SEMICOL = 56;
  public static final int GRTR = 12;
  public static final int PLUS = 7;
  public static final int MAIN = 47;
  public static final int IF = 42;
  public static final int ASSIGN = 17;
  public static final int GRTR_EQL = 14;
  public static final int DOT = 25;
  public static final int ID = 28;
  public static final int L_BRKT = 52;
  public static final int EOF = 0;
  public static final int RETURN = 5;
  public static final int INT_CONST = 29;
  public static final int error = 1;
  public static final int NEWLINE = 59;
  public static final int R_BRKT = 53;
  public static final int TEXT_LITERAL = 27;
  public static final int MOD = 10;
  public static final int BREAK = 32;
  public static final int VOID = 23;
  public static final int SWITCH = 45;
  public static final int COL = 57;
  public static final int REAL = 21;
  public static final int TIMES = 8;
  public static final int ARROW = 24;
  public static final int L_BRACE = 50;
  public static final int FOREACH = 40;
  public static final int ELSE = 43;
  public static final int R_BRACE = 51;
  public static final int FUNCTIONS = 46;
  public static final int WHILE = 38;
  public static final int LIST = 22;
  public static final int DEFAULT = 34;
  public static final int REAL_CONST = 30;
  public static final int BOOL_CONST = 31;
  public static final int TEXT = 18;
  public static final int REDUCE = 49;
  public static final int NOT_EQLS = 16;
  public static final int DBL_EQLS = 15;
}

