
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 13 17:25:14 EDT 2012
//----------------------------------------------------

package front_end;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LESS_EQL = 11;
  public static final int MAP = 49;
  public static final int DIVIDE = 7;
  public static final int CHAR = 27;
  public static final int UMINUS = 23;
  public static final int L_PAREN = 55;
  public static final int CASE = 34;
  public static final int CONTINUE = 5;
  public static final int R_PAREN = 56;
  public static final int DECR = 2;
  public static final int INT = 18;
  public static final int INCR = 3;
  public static final int FOR = 40;
  public static final int LESS = 9;
  public static final int MINUS = 22;
  public static final int NOT = 38;
  public static final int AND = 36;
  public static final int ELSEIF = 45;
  public static final int IN = 42;
  public static final int OR = 37;
  public static final int COMMA = 59;
  public static final int BOOL = 17;
  public static final int SEMICOL = 57;
  public static final int GRTR = 10;
  public static final int PLUS = 24;
  public static final int MAIN = 48;
  public static final int IF = 43;
  public static final int ASSIGN = 15;
  public static final int GRTR_EQL = 12;
  public static final int DOT = 26;
  public static final int ID = 29;
  public static final int L_BRKT = 53;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int INT_CONST = 30;
  public static final int error = 1;
  public static final int NEWLINE = 60;
  public static final int R_BRKT = 54;
  public static final int TEXT_LITERAL = 28;
  public static final int MOD = 8;
  public static final int BREAK = 33;
  public static final int VOID = 21;
  public static final int SWITCH = 46;
  public static final int COL = 58;
  public static final int REAL = 19;
  public static final int TIMES = 6;
  public static final int ARROW = 25;
  public static final int L_BRACE = 51;
  public static final int FOREACH = 41;
  public static final int ELSE = 44;
  public static final int R_BRACE = 52;
  public static final int FUNCTIONS = 47;
  public static final int WHILE = 39;
  public static final int LIST = 20;
  public static final int DEFAULT = 35;
  public static final int REAL_CONST = 31;
  public static final int BOOL_CONST = 32;
  public static final int TEXT = 16;
  public static final int REDUCE = 50;
  public static final int NOT_EQLS = 14;
  public static final int DBL_EQLS = 13;
}

