
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Mar 14 16:51:47 EDT 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 18;
  public static final int CHAR = 37;
  public static final int SEMI = 19;
  public static final int INT = 35;
  public static final int ARRAY = 3;
  public static final int LESS = 27;
  public static final int MINUS = 17;
  public static final int AND = 2;
  public static final int TYPE = 13;
  public static final int OR = 9;
  public static final int COMMA = 20;
  public static final int BEGIN = 4;
  public static final int PLUS = 16;
  public static final int IF = 7;
  public static final int DOT = 33;
  public static final int OF = 8;
  public static final int EOF = 0;
  public static final int GTR = 26;
  public static final int error = 1;
  public static final int PROGRAM = 10;
  public static final int LEFT_BRKT = 23;
  public static final int RT_PAREN = 22;
  public static final int IDENT = 34;
  public static final int EQ = 25;
  public static final int ASSMNT = 32;
  public static final int REAL = 36;
  public static final int TIMES = 15;
  public static final int COLON = 31;
  public static final int ELSE = 5;
  public static final int NOT_EQ = 30;
  public static final int LESS_EQ = 28;
  public static final int RT_BRKT = 24;
  public static final int THEN = 12;
  public static final int END = 6;
  public static final int LEFT_PAREN = 21;
  public static final int GTR_EQ = 29;
  public static final int VAR = 14;
  public static final int PROCEDURE = 11;
}

